services:
  ethoscope-virtual:
    build:
      context: .
      dockerfile: virtuascope.dockerfile
      args:
        - ETHOSCOPE_BRANCH=dev
    image: ethoscope-device
    container_name: ethoscope-device
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ../../:/opt/ethoscope:ro  # Uncomment if needed - will mount the host ethoscope folder, useful only for development
      - ethoscope_data:/ethoscope_data
    devices:
      #- /dev/video0:/dev/video0   # Use video hardware on the computer
      - /dev/video10:/dev/video0  # Use virtual video device
    depends_on:
      - video-streamer
    #network_mode: host

  video-streamer:
    build:
      context: .
      dockerfile: video-streamer.dockerfile
    container_name: ethoscope-video-streamer
    # privileged: true  # No longer needed - device created on host
    environment:
      - VIDEO_URL=/video/raw-ethoscope-video.mkv # 10 minute ethoscope raw video sample from youtube
      - VIRTUAL_DEVICE=/dev/video10
      - LOOP=true  # Set to false for single playback
    devices:
      - /dev/video10:/dev/video10
    volumes:
      - ./video:/video #yt-dlp "https://www.youtube.com/watch?v=uGsWPLsU6ws" -o ./video/raw-ethoscope-video.mkv
    restart: unless-stopped

volumes:
  ethoscope_data:

networks:
  default:
    name: ethoscope_network
    external: true
